### ISSUE TITLE
can't modify 'option' value in step

### ISSUE THREAD

**Issue by edbalogh** [dafreels/metalus-api#3]
I am not able to update the value for an 'object' parameter.  In the screenshot below, the edit button doesn't do anything (I'm in Chrome if that matters)

![Screen Shot 2019-10-09 at 10 43 37 AM](https://user-images.githubusercontent.com/2118102/66492113-de229580-ea81-11e9-978e-ccf0f8794933.png)

**Comment by dafreels** [comment]
This has been fixed in the Beta release
