### ISSUE TITLE
applications-editor

### ISSUE THREAD

**Issue by laopeng2021** [dafreels/metalus-api#98]
Is applications-editor under development?
Look at this menu, it is commented out.

When is the expected application-editor menu available? Thank you

<a mat-menu-item [routerLink]="['/']" routerLinkActive="active">
      <mat-icon color="primary">home</mat-icon>
      <span class="spacer">Home</span>
  </a>
  
  
  
  
  
  
  
  <a mat-menu-item [routerLink]="['/pipelines-editor']"

**Comment by dafreels** [comment]
Duplicate of #5
